In [1]:
def LUpartial(A):
    """
    Funzione che esegue la fattorizzazione LU con pivot parziale di una data matrice.
 
    Input data:
    A   square non-singular matrix
     
    Output data:
    L   lower triangular matrix with det(L)=1
    U   upper triangular matrix with det(L)!=0
    P   permutation matrix
 
     """
    
    (n,m)=A.shape    #gets rows and columns of the given matrix

    #checks that the given matrix is square
    if (n != m):
        print("The given matrix is not square.\n", 
               "LU factorization need a square non-singular matrix to work.")
        return (None, None, None)

    #initializes matrices
    U = np.copy(A)      #copies A elements into U
    L = np.zeros([n,n]) #creates L as a 0-made matrix 
    P = np.eye(n)       #creates permutation matrix
    for i in range (0,n):
        print("\nStep", i+1)
        maxIndex=np.argmax(np.abs(U[i:,i])) #finds the index of the maximum partial pivot 

        P[ [i, maxIndex+i],:] =P[[maxIndex+i,i],:]   #permutates P rows

        U[ [i,maxIndex+i],:]  =U[[maxIndex+i,i],:]  #permutates U rows

        L[[i, maxIndex+i],:]  =L[[maxIndex+i,i],:]   #permutates L rows
        
        print("L:\n", L)
        print("U:\n", U)
        print("P:\n", P)


        if abs(np.float64(U[i,i])) < np.finfo(np.float64(U[i,i])).eps:
            print("Couldn't execute LU factorization with partial pivot.\n", 
                  "The matrix could have scaling problems or be singular!")
            return (None, None, None)


        L[(i+1):n,i] = U[(i+1):n,i]/U[i,i] #calculates L elements

        #overwrites U with the new one
        U[(i+1):n,(i+1):n]=U[(i+1):n,(i+1):n]-np.outer(L[(i+1):n,i],U[i,(i+1):n]) #updates the second block of the second row

        U[(i+1):n,i]=0 #sets to 0 the first block of the second row

    L=L+np.eye(n)   #adds identity to L to put ones on diagonal
    return (L,U,P)

In [2]:
def testLU(L, U, P):
    LU=np.dot(L, U)  #matrices product

    #permutates LU using P
    print("Permutated L and U product:\n", np.dot(np.transpose(P), LU))

## Factorization

In [3]:
import numpy as np
import scipy.linalg as las

#insert here your matrix to factorize
A=np.matrix('1 -0.5 -2; 0.5 -1 -1.75; 2 -5 8')

L, U, P=LUpartial(A)
print("Final result\n")
print("L:\n", L)
print("U:\n", U)
print("P:\n", P)


Step 1
L:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U:
 [[ 2.   -5.    8.  ]
 [ 0.5  -1.   -1.75]
 [ 1.   -0.5  -2.  ]]
P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Step 2
L:
 [[0.   0.   0.  ]
 [0.5  0.   0.  ]
 [0.25 0.   0.  ]]
U:
 [[ 2.   -5.    8.  ]
 [ 0.    2.   -6.  ]
 [ 0.    0.25 -3.75]]
P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Step 3
L:
 [[0.    0.    0.   ]
 [0.5   0.    0.   ]
 [0.25  0.125 0.   ]]
U:
 [[ 2. -5.  8.]
 [ 0.  2. -6.]
 [ 0.  0. -3.]]
P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Final result

L:
 [[1.    0.    0.   ]
 [0.5   1.    0.   ]
 [0.25  0.125 1.   ]]
U:
 [[ 2. -5.  8.]
 [ 0.  2. -6.]
 [ 0.  0. -3.]]
P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


## Test factorization

In [4]:
#insert here your matrices to test
L=np.matrix('1 0 0 0; 0.5 1 0 0; 0.75 0.5 1 0; 0 0.5 0.5 1')
U=np.matrix('4 0 1 1; 0 2 3.5 0.5; 0 0 0.5 0; 0 0 0 -0.25')
P=np.matrix('1 0 0 0; 0 0 0 1; 0 1 0 0; 0 0 1 0')

testLU(L,U,P)

Permutated L and U product:
 [[4. 0. 1. 1.]
 [3. 1. 3. 1.]
 [0. 1. 2. 0.]
 [2. 2. 4. 1.]]
